language: node_js
node_js:
  - "node"
services:
  - postgresql
before_script:
  - npm install -g typescript
  - psql -U postgres -c 'CREATE DATABASE spont_test;'
  - psql -U postgres spont_test -c "create extension uuid-ossp"
notifications:
  email: false
